# application.local.yml
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: post0093265
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
