# application.railway.yml
spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: jdbc:${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}
