spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: eTmAcHFXMslfAjTOAenVLxIHFrYBPqug
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}
